-- migrations/008_webauthn.sql
-- Phase 2b.14: WebAuthn (FIDO2 / passkeys) as a second 2FA option.
--
-- Design notes:
--   * webauthn_credentials holds one row per registered authenticator.
--     credential_id is the WebAuthn-assigned opaque blob (raw bytes,
--     not base64) — UNIQUE across all users so we can look a creds up
--     during the auth ceremony without needing the userId first
--     (supports usernameless flows down the road).
--   * public_key is the COSE-encoded public key as returned by the
--     attestation. Stored AS-IS — verification against assertions does
--     not need it parsed.
--   * counter is the FIDO signature counter. Some hardware authenticators
--     return 0 forever (TPMs/passkeys often do); we still store it but
--     a regression is just a warning, not a hard error, in the verify
--     path. BIGINT so we never wrap.
--   * transports / aaguid are advisory metadata for UX (icon hints, etc.)
--     and excludeCredentials hints during register. NULLable since older
--     authenticators don't always provide them.
--   * backup_eligible / backup_state come from the WebAuthn flags byte
--     (BE / BS). Surfaced for "this passkey is synced to your iCloud" UI
--     and for security review (a sync-eligible cred has different threat
--     model than a hardware-only one).
--   * `name` is user-supplied at register time ("Yubikey 5", "MacBook
--     Touch ID"). NULL is allowed and the UI falls back to the aaguid
--     vendor or a serial.
--   * created_at / last_used_at give the user a sensible "credentials"
--     panel — we update last_used_at on every successful authenticate.
--
--   * webauthn_challenges holds short-lived challenges generated by
--     /register/options and /authenticate/options. Stored server-side
--     (rather than echoed in a cookie) so we get atomic single-use
--     consumption — a stolen challenge can't be replayed across sessions.
--     user_id is NULLable because authenticate/options runs against a
--     pre_2fa session whose user we DO know, but conceptually we want
--     to keep both kinds in one table for the cleanup sweep.
--   * kind: 'register' or 'authenticate' — kept distinct so a register
--     challenge can never satisfy an authenticate verify.
--   * expires_at: 2 minutes by default; cleaned up by the same sweep
--     that handles sessions.
--
--   * sessions.stage already supports 'pre_2fa' (added in 007). WebAuthn
--     reuses the existing pre-session machinery — same cookie, same TTL —
--     with a separate /authenticate/verify endpoint to promote.
--
-- Idempotent.

CREATE TABLE IF NOT EXISTS webauthn_credentials (
  id                BIGSERIAL    PRIMARY KEY,
  user_id           UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_id     BYTEA        NOT NULL UNIQUE,
  public_key        BYTEA        NOT NULL,
  counter           BIGINT       NOT NULL DEFAULT 0,
  transports        TEXT[],                      -- e.g. {'usb','nfc','internal'}
  aaguid            UUID,                        -- vendor / model id; NULL for older keys
  name              TEXT,                        -- user-friendly label
  backup_eligible   BOOLEAN      NOT NULL DEFAULT false,
  backup_state      BOOLEAN      NOT NULL DEFAULT false,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  last_used_at      TIMESTAMPTZ
);

-- "All credentials for a user" is the hot path during /authenticate/options
-- (we send allowCredentials so the right authenticator is picked).
CREATE INDEX IF NOT EXISTS webauthn_credentials_user_idx
  ON webauthn_credentials (user_id);

CREATE TABLE IF NOT EXISTS webauthn_challenges (
  id          BIGSERIAL    PRIMARY KEY,
  user_id     UUID         REFERENCES users(id) ON DELETE CASCADE,  -- nullable on purpose
  challenge   BYTEA        NOT NULL,
  kind        TEXT         NOT NULL CHECK (kind IN ('register', 'authenticate')),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ  NOT NULL,
  consumed_at TIMESTAMPTZ                                           -- NULL = unused
);

-- Single-row lookup keyed by (user_id, kind) for the verify path.
CREATE INDEX IF NOT EXISTS webauthn_challenges_user_kind_idx
  ON webauthn_challenges (user_id, kind) WHERE consumed_at IS NULL;

-- Sweep target.
CREATE INDEX IF NOT EXISTS webauthn_challenges_expires_idx
  ON webauthn_challenges (expires_at) WHERE consumed_at IS NULL;
